// Export pages
export '/pages/login_page/login_page_widget.dart' show LoginPageWidget;
export '/pages/set_pin_code_page/set_pin_code_page_widget.dart'
    show SetPinCodePageWidget;
export '/pages/pin_code_page/pin_code_page_widget.dart' show PinCodePageWidget;
export '/pages/branch_view/dashboard/dashboard_widget.dart'
    show DashboardWidget;
export '/pages/branch_view/check_in_page/check_in_page_widget.dart'
    show CheckInPageWidget;
export '/pages/branch_view/survey_page/survey_page_widget.dart'
    show SurveyPageWidget;
export '/pages/super_app/super_app_page/super_app_page_widget.dart'
    show SuperAppPageWidget;
export '/pages/super_app/notification_detail_page/notification_detail_page_widget.dart'
    show NotificationDetailPageWidget;
export '/pages/profile_page_folder/my_profile_page/my_profile_page_widget.dart'
    show MyProfilePageWidget;
export '/pages/super_app/lead_noti_page/lead_noti_page_widget.dart'
    show LeadNotiPageWidget;
export '/pages/branch_view/collection_page/collection_page_widget.dart'
    show CollectionPageWidget;
export '/pages/branch_view/marketing_page/marketing_page_widget.dart'
    show MarketingPageWidget;
export '/pages/branch_view/o_p_spage/o_p_spage_widget.dart' show OPSpageWidget;
export '/pages/branch_view/checker_page/checker_page_widget.dart'
    show CheckerPageWidget;
export '/pages/branch_view/n_p_apage/n_p_apage_widget.dart' show NPApageWidget;
export '/pages/branch_view/time_sheet_page/time_sheet_page_widget.dart'
    show TimeSheetPageWidget;
export '/pages/branch_view/forgot_password_page/forgot_password_page_widget.dart'
    show ForgotPasswordPageWidget;
export '/pages/branch_view/success_page/success_page_widget.dart'
    show SuccessPageWidget;
export '/pages/super_app/form_service_page/form_service_page_widget.dart'
    show FormServicePageWidget;
export '/pages/super_app/gen_q_r_page/gen_q_r_page_widget.dart'
    show GenQRPageWidget;
export '/pages/super_app/lead_survey_regis_page/lead_survey_regis_page_widget.dart'
    show LeadSurveyRegisPageWidget;
export '/pages/super_app/saleskit_page/saleskit_page_widget.dart'
    show SaleskitPageWidget;
export '/pages/super_app/i_t_support_page/i_t_support_page_widget.dart'
    show ITSupportPageWidget;
export '/pages/action_log_page/action_log_page_widget.dart'
    show ActionLogPageWidget;
export '/pages/super_app/introdution_page/introdution_page_widget.dart'
    show IntrodutionPageWidget;
export '/pages/super_app/report_i_t_support/report_i_t_support_widget.dart'
    show ReportITSupportWidget;
export '/pages/leave_app/leave_page/leave_page_widget.dart'
    show LeavePageWidget;
export '/pages/check_in/success_checkin_page/success_checkin_page_widget.dart'
    show SuccessCheckinPageWidget;
export '/pages/check_in/empolyee_check_in/empolyee_check_in_widget.dart'
    show EmpolyeeCheckInWidget;
export '/pages/leave_app/leave_show_page/leave_show_page_widget.dart'
    show LeaveShowPageWidget;
export '/pages/leave_app/add_leave_page/add_leave_page_widget.dart'
    show AddLeavePageWidget;
export '/pages/leave_app/cancel_page/cancel_page_widget.dart'
    show CancelPageWidget;
export '/pages/leave_app/approved_leave_page/approved_leave_page_widget.dart'
    show ApprovedLeavePageWidget;
export '/pages/insurance/check_insurance_page/check_insurance_page_widget.dart'
    show CheckInsurancePageWidget;
export '/pages/insurance/check_1_insurance_page/check1_insurance_page_widget.dart'
    show Check1InsurancePageWidget;
export '/pages/leave_app/confirm_email_page/confirm_email_page_widget.dart'
    show ConfirmEmailPageWidget;
export '/pages/info_checkin/info_checkin_widget.dart' show InfoCheckinWidget;
export '/pages/insurance/list_insuranc_page/list_insuranc_page_widget.dart'
    show ListInsurancPageWidget;
export '/pages/find_place_page/find_place_page_widget.dart'
    show FindPlacePageWidget;
export '/pages/insurance/detail_insurance_page/detail_insurance_page_widget.dart'
    show DetailInsurancePageWidget;
export '/pages/i_t_support/dashboard_i_t_support/dashboard_i_t_support_widget.dart'
    show DashboardITSupportWidget;
export '/pages/check_in/check_in_status_page/check_in_status_page_widget.dart'
    show CheckInStatusPageWidget;
export '/pages/i_t_support/category_support/category_support_widget.dart'
    show CategorySupportWidget;
export '/pages/i_t_support/report_list/report_list_widget.dart'
    show ReportListWidget;
export '/pages/i_t_support/info_report/info_report_widget.dart'
    show InfoReportWidget;
export '/pages/check_in/check_in_status_page_copy/check_in_status_page_copy_widget.dart'
    show CheckInStatusPageCopyWidget;
export '/pages/check_in/dashboard_checkin/dashboard_checkin_widget.dart'
    show DashboardCheckinWidget;
export '/pages/promotion_page/promotion_page_widget.dart'
    show PromotionPageWidget;
export '/pages/super_app/employee_k_p_i_page/employee_k_p_i_page_widget.dart'
    show EmployeeKPIPageWidget;
export '/pages/profile_page_folder/guide_book_page/guide_book_page_widget.dart'
    show GuideBookPageWidget;
export '/pages/leave_app/add_resign_page/add_resign_page_widget.dart'
    show AddResignPageWidget;
export '/pages/leave_app/dashboard_leave_page/dashboard_leave_page_widget.dart'
    show DashboardLeavePageWidget;
export '/pages/leave_app/approve_show_page/approve_show_page_widget.dart'
    show ApproveShowPageWidget;
export '/pages/leave_app/add_resign_page_copy/add_resign_page_copy_widget.dart'
    show AddResignPageCopyWidget;
export '/pages/leave_app/edit_leave_page/edit_leave_page_widget.dart'
    show EditLeavePageWidget;
export '/pages/i_t_support/form_it_support/form_it_support_widget.dart'
    show FormItSupportWidget;
export '/pages/point_app/sum_point_page/sum_point_page_widget.dart'
    show SumPointPageWidget;
export '/pages/point_app/quota_point_page/quota_point_page_widget.dart'
    show QuotaPointPageWidget;
export '/pages/super_app/welfare_k_p_i_page/welfare_k_p_i_page_widget.dart'
    show WelfareKPIPageWidget;
export '/pages/point_app/give_point_page/give_point_page_widget.dart'
    show GivePointPageWidget;
export '/pages/profile_page_folder/insurance_plan/insurance_plan_widget.dart'
    show InsurancePlanWidget;
export '/pages/questionnaire_survey/questionnaire_survey_widget.dart'
    show QuestionnaireSurveyWidget;
export '/pages/phone_number_info/phone_number_info_widget.dart'
    show PhoneNumberInfoWidget;
export '/pages/e_learning/e_learning_widget.dart' show ELearningWidget;
export '/pages/support_template/support_template_widget.dart'
    show SupportTemplateWidget;
export '/pages/super_app/html_page/html_page_widget.dart' show HtmlPageWidget;
export '/pages/employee_kpi_c_e_o_page/employee_kpi_c_e_o_page_widget.dart'
    show EmployeeKpiCEOPageWidget;
export '/pages/super_app/welfare_k_p_i_c_e_o_page/welfare_k_p_i_c_e_o_page_widget.dart'
    show WelfareKPICEOPageWidget;
export '/pages/ertert/ertert_widget.dart' show ErtertWidget;
export '/pages/super_app/inspoc_page/inspoc_page_widget.dart'
    show InspocPageWidget;
export '/pages/check_in/change_lat_lng_page/change_lat_lng_page_widget.dart'
    show ChangeLatLngPageWidget;
export '/pages/super_app/classroom_page/classroom_page_widget.dart'
    show ClassroomPageWidget;
export '/pages/test_circle_map/test_circle_map_widget.dart'
    show TestCircleMapWidget;
export '/pages/point_app/redeem_point_page/redeem_point_page_widget.dart'
    show RedeemPointPageWidget;
export '/pages/planning_self_k_p_i/planning_self_k_p_i_widget.dart'
    show PlanningSelfKPIWidget;
export '/pages/thaipaiboon_insurance/thaipaiboon_page/thaipaiboon_page_widget.dart'
    show ThaipaiboonPageWidget;
export '/pages/leave_app/leave_show_page_copy/leave_show_page_copy_widget.dart'
    show LeaveShowPageCopyWidget;
export '/pages/profile_page_folder/life_insurance_license_card_page/life_insurance_license_card_page_widget.dart'
    show LifeInsuranceLicenseCardPageWidget;
export '/pages/check_in/change_lat_lng_page_web/change_lat_lng_page_web_widget.dart'
    show ChangeLatLngPageWebWidget;
export '/sawad_chat/chat_search_page/chat_search_page_widget.dart'
    show ChatSearchPageWidget;
export '/sawad_chat/chat_home_page/chat_home_page_widget.dart'
    show ChatHomePageWidget;
export '/sawad_chat/chatting_page/chatting_page_widget.dart'
    show ChattingPageWidget;
export '/pages/insurance_agent/insurance_request_insurer_page/insurance_request_insurer_page_widget.dart'
    show InsuranceRequestInsurerPageWidget;
export '/pages/insurance_agent/insurance_request_image_page/insurance_request_image_page_widget.dart'
    show InsuranceRequestImagePageWidget;
export '/pages/insurance_agent/insurance_request_basic_page/insurance_request_basic_page_widget.dart'
    show InsuranceRequestBasicPageWidget;
export '/pages/insurance_agent/insurance_request_list_page/insurance_request_list_page_widget.dart'
    show InsuranceRequestListPageWidget;
export '/pages/insurance_agent/insurance_request_dashboard_page/insurance_request_dashboard_page_widget.dart'
    show InsuranceRequestDashboardPageWidget;
export '/pages/insurance_agent/insurance_request_edit_page/insurance_request_edit_page_widget.dart'
    show InsuranceRequestEditPageWidget;
export '/pages/inbox_email/inbox_email_widget.dart' show InboxEmailWidget;
export '/pages/super_app/search_insurance_page/search_insurance_page_widget.dart'
    show SearchInsurancePageWidget;
export '/pages/super_app/about_us_page/about_us_page_widget.dart'
    show AboutUsPageWidget;
export '/pages/super_app/contact_us_page/contact_us_page_widget.dart'
    show ContactUsPageWidget;
export '/pages/super_app/i_b_s_report/i_b_s_report_widget.dart'
    show IBSReportWidget;
export '/k_p_i_all_c_e_o_page/k_p_i_all_c_e_o_page_widget.dart'
    show KPIAllCEOPageWidget;
export '/pages/super_app/bsi_report_page/bsi_report_page_widget.dart'
    show BsiReportPageWidget;
export '/collection_page/list_name_tab_follow_up_debt/list_name_tab_follow_up_debt_widget.dart'
    show ListNameTabFollowUpDebtWidget;
export '/record_video_webview_page/record_video_webview_page_widget.dart'
    show RecordVideoWebviewPageWidget;
export '/collection_page/detail_list_follow_up_debt/detail_list_follow_up_debt_widget.dart'
    show DetailListFollowUpDebtWidget;
export '/collection_page/save_on_site_follow_up_debt/save_on_site_follow_up_debt_widget.dart'
    show SaveOnSiteFollowUpDebtWidget;
export '/collection_page/save_call_follow_up_debt/save_call_follow_up_debt_widget.dart'
    show SaveCallFollowUpDebtWidget;
export '/collection_page/record_follow_up_debt/record_follow_up_debt_widget.dart'
    show RecordFollowUpDebtWidget;
export '/collection_page/success_page_collecction/success_page_collecction_widget.dart'
    show SuccessPageCollecctionWidget;
export '/collection_page/tab_collection/tab_collection_widget.dart'
    show TabCollectionWidget;
export '/collection_page/search_collection_page/search_collection_page_widget.dart'
    show SearchCollectionPageWidget;
export '/collection_page/search_collection_p_p/search_collection_p_p_widget.dart'
    show SearchCollectionPPWidget;
export '/pages/register/register_widget.dart' show RegisterWidget;
export '/collection_page/interest_page/interest_page_widget.dart'
    show InterestPageWidget;
export '/collection_page/q_r_code/q_r_code_widget.dart' show QRCodeWidget;
export '/record_video_page/record_video_page_widget.dart'
    show RecordVideoPageWidget;
export '/camera_video_record/record_video_customer/record_video_customer_widget.dart'
    show RecordVideoCustomerWidget;
export '/camera_video_record/record_video_customer2/record_video_customer2_widget.dart'
    show RecordVideoCustomer2Widget;
export '/camera_video_record/record_video_customer3/record_video_customer3_widget.dart'
    show RecordVideoCustomer3Widget;
export '/pages/super_app/super_app_new_page/super_app_new_page_widget.dart'
    show SuperAppNewPageWidget;
export '/webview_page/webview_page_widget.dart' show WebviewPageWidget;
export '/pages/super_app/roadmapinsurance/roadmapinsurance_widget.dart'
    show RoadmapinsuranceWidget;
export '/car_seized/car_seized_page_step1/car_seized_page_step1_widget.dart'
    show CarSeizedPageStep1Widget;
export '/car_seized/car_seized_dashboard_page/car_seized_dashboard_page_widget.dart'
    show CarSeizedDashboardPageWidget;
export '/car_seized/customer_car_deails_step1/customer_car_deails_step1_widget.dart'
    show CustomerCarDeailsStep1Widget;
export '/car_seized/sample_car_image_step1/sample_car_image_step1_widget.dart'
    show SampleCarImageStep1Widget;
export '/car_seized/customer_car_deails_step4/customer_car_deails_step4_widget.dart'
    show CustomerCarDeailsStep4Widget;
export '/car_seized/type_pic_step1/type_pic_step1_widget.dart'
    show TypePicStep1Widget;
export '/car_seized/customer_bike_details_step1/customer_bike_details_step1_widget.dart'
    show CustomerBikeDetailsStep1Widget;
export '/car_seized/customer_bike_deails_step4/customer_bike_deails_step4_widget.dart'
    show CustomerBikeDeailsStep4Widget;
export '/car_seized/car_seized_select_dashboard/car_seized_select_dashboard_widget.dart'
    show CarSeizedSelectDashboardWidget;
export '/car_seized/search_customers_g_d/search_customers_g_d_widget.dart'
    show SearchCustomersGDWidget;
export '/car_seized/customer_car_deails_picture_step1/customer_car_deails_picture_step1_widget.dart'
    show CustomerCarDeailsPictureStep1Widget;
export '/car_seized/customer_car_deails_picture_step12/customer_car_deails_picture_step12_widget.dart'
    show CustomerCarDeailsPictureStep12Widget;
export '/car_seized/change_car_location_page/change_car_location_page_widget.dart'
    show ChangeCarLocationPageWidget;
export '/calendar_page/calendar_page_widget.dart' show CalendarPageWidget;
export '/test_page/test_page_widget.dart' show TestPageWidget;
export '/scan_q_r/scan_q_r_widget.dart' show ScanQRWidget;
export '/car_seized/branch_selected_page/branch_selected_page_widget.dart'
    show BranchSelectedPageWidget;
export '/pages/super_app/webview_new_page/webview_new_page_widget.dart'
    show WebviewNewPageWidget;
export '/tracking_emp_page/tracking_emp_page_widget.dart'
    show TrackingEmpPageWidget;
export '/pages/search_employee_page/search_employee_page_widget.dart'
    show SearchEmployeePageWidget;
export '/pages/search_employee_page2/search_employee_page2_widget.dart'
    show SearchEmployeePage2Widget;
export '/searchableemp/searchableemp_widget.dart' show SearchableempWidget;
export '/pages/branch_view/remark_type_d_page/remark_type_d_page_widget.dart'
    show RemarkTypeDPageWidget;
export '/pages/super_app/lead_noti_new_page/lead_noti_new_page_widget.dart'
    show LeadNotiNewPageWidget;
export '/pages/super_app/webview_new_page_copy/webview_new_page_copy_widget.dart'
    show WebviewNewPageCopyWidget;
export '/gen_q_r_customer/search_q_r_customer_page/search_q_r_customer_page_widget.dart'
    show SearchQRCustomerPageWidget;
export '/gen_q_r_customer/detail_q_r_customer_page/detail_q_r_customer_page_widget.dart'
    show DetailQRCustomerPageWidget;
export '/gen_q_r_customer/payment_q_rcode/payment_q_rcode_widget.dart'
    show PaymentQRcodeWidget;
export '/sawad_chat/group_chat_add_page/group_chat_add_page_widget.dart'
    show GroupChatAddPageWidget;
export '/sawad_chat/chat_room_setting_page/chat_room_setting_page_widget.dart'
    show ChatRoomSettingPageWidget;
export '/selfie_mask_page/selfie_mask_page_widget.dart'
    show SelfieMaskPageWidget;
export '/car_seized/customer_car_deails_document_step1/customer_car_deails_document_step1_widget.dart'
    show CustomerCarDeailsDocumentStep1Widget;
export '/sawad_chat/add_people_page/add_people_page_widget.dart'
    show AddPeoplePageWidget;
export '/collection_page/r_p72_check_list_page/r_p72_check_list_page_widget.dart'
    show RP72CheckListPageWidget;
export '/ew9tf0uewitf/ew9tf0uewitf_widget.dart' show Ew9tf0uewitfWidget;
export '/q_r_complain/q_r_complain_widget.dart' show QRComplainWidget;
export '/sawad_chat/bot_chatting_page/bot_chatting_page_widget.dart'
    show BotChattingPageWidget;
